env: "local"
storage_path: "host=postgres port=5432 user=postgres password=postgres_1234 dbname=Authentication sslmode=disable"
access_token_ttl: 15m
refresh_token_ttl: 168h
grpc:
    port: ":9090"
    timeout: 5s
jwt:
    secret_key: "E3IiecHXTaBytd5Sik50L/YvQTVlzmngF8u6TR+N66w"
mailopost:
    api_url: "https://api.mailopost.ru/v1"  
    api_token: "c263ca13ea017f6d003c2b2802c4943a"        
    from_email: "1kartofan@gmail.com"